backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow
collections:
  - label: "Content"
    name: "content"
    files:
      - label: "Home page"
        name: "homepage"
        format: "json"
        file: "cms/_posts/home.json"
        fields:
          - { label: "Hero Image", name: "heroimage", widget: "image" }
          - { label: "Hero Heading", name: heroheading, widget: string }
          - { label: "Hero Copy", name: herocopy, widget: string }
          - { label: 'Code' name: 'code', widget: 'code'}
