backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow
collections:
  - label: "posts"
    name: "Post"
    create: true
    files:
      - label: "Profile"
        name: "profile"
        widget: "object"
        summary: "{{fields.name}}: {{fields.birthdate}}"
        fields:
          - {
              label: "Public",
              name: "public",
              widget: "boolean",
              default: true,
            }
          - { label: "Name", name: "name", widget: "string" }
          - label: "Birthdate"
            name: "birthdate"
            widget: "date"
            default: ""
            format: "MM/DD/YYYY"
          - label: "Address"
            name: "address"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Street Address", name: "street", widget: "string" }
              - { label: "City", name: "city", widget: "string" }
              - { label: "Postal Code", name: "post-code", widget: "string" }
