backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow
collections:
  - label: "homepage"
    name: "Homepage"
    extension: json
    format: json
    files:
      - label: "content"
        name: "Content"
        file: "cms/_posts/main.json"
        fields:
          - label: "content"
            name: "Content"
            widget: list
            fields:
              - { label: "Message", name: message, widget: string }
              - { label: "Featured Image", name: "thumbnail", widget: "image" }
