backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "posts"
    label: "Post"
    folder: "/cms/_posts"
    filter:
      field: language
      value: en
    files:
      - label: "Info"
        name: "info"
        format: "json"
        file: "content/about.json"
        fields:
          - { label: "Message", name: message, widget: string }
          - { label: "Featured Image", name: "thumbnail", widget: "image" }
publish_mode: editorial_workflow
