backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "cms/_posts"
    format: json
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
